### ISSUE TITLE
Stack overflow when parsing a deeply nested toml_edit::Document

### ISSUE THREAD

**Issue by 5225225** [toml-rs/toml#206]
Basically the same error as seen as https://github.com/alexcrichton/toml-rs/issues/428

Reproduction code:

```rust
fn main() {
    let brackets = "[".repeat(20000);
    let input_string = format!("x={}", &brackets);
    input_string.parse::<toml_edit::Document>().unwrap();
}
```

**Comment by epage** [comment]
I assume this is also true for `{` (inline tables).

Likewise, it'd take longer but I assume we'd also hit OOM for many dotted keys, many tables, and many key-values.

For dotted keys, I'm actually unsure whether we would hit OOM (too many keys for memory) or stack overflow (recursively walking data structures) first.

**Comment by ordian** [comment]
The issue is about stackoverflow, not OOM.

 A solution to this problem is to use an explicit stack (using a vec) instead of recursion.

**Comment by epage** [comment]
I brought up OOM because
- Stackoverflow is a special case of OOM
- Because we generally don't handle OOM errors in Rust, they lead to the same behavior (crash)
- Changing recursion to explicit stack just converts the problem from stackoverflow to OOM, it will just take longer to crash without the stack frame boilerplate

The main reason I can think of to handle stackoverflows specially is to provide a good error on accidental infinite recursion so people can get out of that case, which is not applicable here.

We can easily change descend-path from recursion but parsing of inline tables and arrays will be more difficult.

**Comment by ordian** [comment]
Well, by OOM, people usually mean Out Of (heap) Memory. 
And one of the differences between the stack and the heap is that the default stack size is fixed and relatively small (8MiB), whereas the heap size is usually limited by the amount of RAM a computer has (yeah, it's more complicated than that).

So I would say, ensuring no stackoverflow is almost always lib's responsibility, as opposed to ensure no OO(heap)M.

**Comment by ordian** [comment]
We could use something like https://github.com/rust-lang/stacker for this.

**Comment by epage** [comment]
Yes, anything that will cause too much recursion will cause an overflow.

Speaking of ways of solving this, I've been thinking of switching this to nom once some ergoomic issues are resolved.  I suspect I could more easily write a heap-allocated recursive parser with it.  We'll see.

**Comment by 5225225** [comment]
That being said, it might *also* be worth adding recursion limits by default, since if you have a deeply nested object, you might run into issues working with it (`drop` being recursive and blowing the stack without taking care, for example).

I would be surprised if any object nested more than, say, 100 deep is actually legitimate. And if someone really does have objects nested that deep, they can disable the limits and be careful themselves.
