### ISSUE TITLE
TOML array can be deserialized to Rust struct

### ISSUE THREAD

**Issue by PopFlamingo** [toml-rs/toml#373]
Hi!

I noticed that a TOML array can be deserialized to a Rust struct, but I believe this should fail.

Here is an example demonstrating the issue:
```rs
#[derive(Deserialize)]
struct Container {
    a: InnerStruct,
}

#[derive(Deserialize)]
struct InnerStruct {
    foo: String,
    bar: String,
}

#[test]
#[should_panic]
fn test() {
    let test_string = r#"
    a = ["ABC", "XYZ"]
    "#;

    // Unwrap doesn't fail here, instead foo contains "ABC" and bar contains "XYZ"
    toml::from_str::<Container>(test_string).unwrap();
}
```

**Comment by epage** [comment]
Previously, `toml::Deserializer` would deserialize a document.  If a type was incompatible with a document, it would deserialize it as a value

#457, this is more explicit with `toml::Deserializer` only deserializing a document and `toml::ValueDeserializer` that only deserializes values.   This should remove the ambiguity that this issue is running into.

Closing as this seems to be resolved in `main`.  If I missed something, let me know and we can re-open.
