### ISSUE TITLE
Unsupported type on already derived Serialize type

### ISSUE THREAD

**Issue by Dennis-Zhang-SH** [toml-rs/toml#534]
```rust
#[derive(Debug, Args, Serialize)]
struct Server {
    server_name: String,
    #[arg(value_parser  = parse_ip)]
    server_address: IpAddr,
    port: u32,
    #[command(subcommand)]
    connect_methods: ConnectMethods,
}

#[derive(Debug, Parser, Serialize)]
#[command(about = "connect methods")]
#[command(name = "connect_methods")]
enum ConnectMethods {
    SSHKey(SSHKey),
    Password(Password),
}
```

I have these 2 types and when I try to `let toml = toml::to_string(&s: Server)?;`, it reports `Error: unsupported ConnectMethods type`.

**Comment by epage** [comment]
Could you provide a complete, minimal reproduction case?  Not having all the types makes it a bit more ambiguous that I'll be helping you with your problem rather than some other problem

**Comment by ozgunozerk** [comment]
I can provide one:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a9c27b8a6032ebfbbef9cea1908be5dc

In this example, u128/i128 support is already present in `serde`. Yet, when used with `toml`, it fails and says u128 is not supported for serialization.

**Comment by epage** [comment]
@ozgunozerk could you create a dedicated issue?  This issue is not about every type of unsupported type but the specific problem @Dennis-Zhang-SH is having.

In fact, without a response, I'm going to close this as there isn't anything I can help them with.  We can always re-open if @Dennis-Zhang-SH does come back with more information.  This way we at least won't get this issue side tracked.
