### ISSUE TITLE
Provide an easy way to deserialize the `toml_edit::Item`

### ISSUE THREAD

**Issue by SomeoneToIgnore** [toml-rs/toml#544]
See https://github.com/toml-rs/toml/pull/543#issuecomment-1506943136

In my application, I have a toml-based config that is getting assembled out of multiple toml pieces and overrides.
I end up having a `toml::Item` constructed in runtime and a need to deserialize it into internal struct.

Before, I could've used `toml_edit::de::from_item` which is now removed and `ValueDeserializer` is provided as an alternative.
Yet, the only possible way to construct this is to convert the `Item` into a `String`, then parse this string into `ValueDeserializer`?
In addition to that, table `Item`s have to be somehow created as inline table form, since the deserializer complains when parsing a regular form.

I propose to make `ValueDeserializer::new` constructor public — if a person has a correct `Item` on hands, it should be able to directly covert it into any `T: DeserializeOwned` or similar.

**Comment by SomeoneToIgnore** [comment]
Here's an example of dynamic construction and further parsing: https://github.com/neondatabase/neon/blob/fd31fafeeeb46ab1f6a68d888dd9b1bf2c1db816/pageserver/src/config.rs#L728

Some of the values per key could be replaced with the overrides, that we're sure is a valid toml, but then we need to parse these possibly-replaced items and `ValueDeserializer` does not help much for table case.

**Comment by epage** [comment]
If you have an `Item`, you can call [`Item::into_value`](https://docs.rs/toml_edit/latest/toml_edit/enum.Item.html#method.into_value) and then use [`IntoDeserializer`](https://docs.rs/toml_edit/latest/toml_edit/enum.Value.html#impl-IntoDeserializer%3C'de,+Error%3E-for-Value) to get `ValueDeserializer`.

The shift in focus away from `Item` was an intentional change due to issues I found in `toml` where it conflated TOML documents and TOML values.  As a result of that, we shifted focus towards Document, Table, and Value as "top level" types to be interacted with.

At the moment, the API focuses on the core workflow and just provides the building blocks for other workflows.  This means that there are extra hoops to go through, like in this case.  As we get input on what people are doing, we can consider re-evaluating some of these.

**Comment by SomeoneToIgnore** [comment]
Thank you so much, that chain of conversions indeed did the trick.
Do you think it's worth editing the https://github.com/toml-rs/toml/blob/5afe783acb09b7e453739c0ca6992f438b1bb6dd/crates/toml_edit/src/de/value.rs#L24-L26 comment to mention this alternative way?
Or is the API too unstable for now?

**Comment by epage** [comment]
It would be fine calling attention to it.

**Comment by SomeoneToIgnore** [comment]
I came up with hopefully the least intrusive way to do so: https://github.com/toml-rs/toml/pull/545
My issue is solved regardless of its merge status, thank you again.
