### ISSUE TITLE
Stringy serialization fails with `Error { inner: UnsupportedType(None) }`

### ISSUE THREAD

**Issue by xmppftw** [toml-rs/toml#562]
Downstream issue: [gitlab.com/xmpp-rs/xmpp-rs#67](https://gitlab.com/xmpp-rs/xmpp-rs/-/issues/67)

In the jid crate, we define three stringy types with different components to be parsed from a `[node@]domain[/resource]` string:

- [BareJid](https://docs.rs/jid/0.9.4/jid/struct.BareJid.html) has a domain and optional node
- [FullJid](https://docs.rs/jid/0.9.4/jid/struct.FullJid.html) has a domain and resource, and optional node
- [Jid](https://docs.rs/jid/0.9.4/jid/enum.Jid.html) is an enum covering these two cases

Serializing the Jid enum works fine, however serializing the BareJid/FullJid fails with error `Error { inner: UnsupportedType(None) }`. This is surprising because:

- Jid derives Serialize (no custom impl) so why does it work if the actual variant implementations fail?
- FullJid/BareJid implement Serialize by [first converting to string](https://gitlab.com/xmpp-rs/xmpp-rs/-/blob/8c18eeecd112fa988e92400a259e8e93b6f32ce3/jid/src/lib.rs#L305), which does not fail

Here's a reproduction case:

```rust
use jid::{Jid, FullJid, BareJid};
use std::str::FromStr;

fn main() {
    let id = Jid::from_str("username@example.com/device").unwrap();
    println!("{} - {:?}", String::from(id.clone()), toml::to_string(&id));

    let id = BareJid::new("username", "example.com");
    println!("{} - {:?}", String::from(&id), toml::to_string(&id));

    let id = FullJid::new("username", "example.com", "device");
    println!("{} - {:?}", String::from(&id), toml::to_string(&id));
}
```

Output:

```
username@example.com/device - Ok("Full = \"username@example.com/device\"\n")
username@example.com - Err(Error { inner: UnsupportedType(None) })
username@example.com/device - Err(Error { inner: UnsupportedType(None) })
```

**Comment by xmppftw** [comment]
Could it be because serializing a simple string without an associated key is not supported? I noticed that this also fails with the same error message:

```rust
    let foo = String::from("test");
    println!("{} - {:?}", &foo, toml::to_string(&foo));
```

I did not find something about string literals without keys in the TOML spec. If so, it's not a bug but rather a quality of life request to have an actually useful error message in this case saying that a key is required.

**Comment by epage** [comment]
Note: v0.5 and before, TOML values and documents were conflated together and this wouldn't have errrored but would have created an invalid TOML document.  We've since made been more strict on the difference which also fixed some corner cases in what we can parse.

For `toml`, we've publicly exposed the error types.  Technically, its exhaustive and we can add new variants *but* this is really a special case of `UnsupportedType`, so I'd rather not change away from that.

When we deserialize, we do so by converting it into a `toml_edit::Value` and then converting that into a `toml_edit::Document`.  This allows us to reuse a lot of code but it prevents us from getting a more precise type to give to `UnsupportedType`.

We could hack in `toml_edit::Value::type_name` but I think that is misleading, telling the user a type in terms of TOML that is unsupported when the error is reporting things in terms of rust types.

I'm inclined to not act on this.
