### ISSUE TITLE
Expose span in Document

### ISSUE THREAD

**Issue by baszalmstra** [toml-rs/toml#571]
If I read the docs correctly it looks like `span` is kept private to the crate is there are reason not to expose this information? It would be beneficial to query a document and ascertain where something is in the document to display friendly diagnostics.

**Comment by epage** [comment]
The priority for implementing span support was for the serde API so that `toml` 0.6 could retain feature parity with 0.5.

However, in doing so, spans slowed things down by quite a bit.  We were able to speed things back up by making spans *exclusive* to the serde API (see #429).  It will take some experimentation and iteration to get span support in the `toml_edit` API without data corruption, panics, and performance loss.

**Comment by dtolnay** [comment]
For now, here is a workaround that makes it possible to access the span of an arbitrary node, using only the existing public API of `toml_edit`. https://play.rust-lang.org/?version=stable&edition=2021&gist=0d457da235449046bd30932a91e45d96

**Comment by epage** [comment]
I wonder if error reporting is faster or using Spanned. I'm assuming error reporting because it won't recurse.

**Comment by epage** [comment]
#698 allows access to spans if you parse with an `ImDocument` as that works around the limitation with exposing spans in `Document`.

Is that sufficient?

**Comment by epage** [comment]
Without further feedback, I'm going to consider this resolved.  If there is a reason we should re-open this, let us know!
