### ISSUE TITLE
Parse mixed array to default parameter

### ISSUE THREAD

**Issue by Alphapage** [toml-rs/toml#582]
Hello,

Here is an example of the toml I want to parse (don't know if it is a valid toml spec):
```
[uplink]
servers = [
  "https://srv1.uplink.com/", # = { url = "https://srv1.uplink.com/", auth_token = "" }
  { url = "https://private.uplink.com/", auth_token = "..." },
]
```
Is it possible to parse and set the first entry to the url property by default as if it was like the commented entry ?

Thank you in advance for your answers.

**Comment by epage** [comment]
Heterogenous arrays was added to the TOML spec in 1.0.0-rc.1 , so this should work.

This is very similar to
```toml
[depedencies]
clap = "4.2"
clap = { version = "4.2" }
```

The way to do this is through an [untagged enum in serde](https://serde.rs/enum-representations.html#untagged).  Note that there is a performance hit for doing this with a derive because it turns it into an if-else-if ladder between each enum variant.  In cases like this, a by-hand implementation can be faster because you can rely on the type being deserialized (e.g. #227).  Of course, focus on performance when it matters ;)

**Comment by Alphapage** [comment]
Many thanks ! I will investigate later to optimize perf
