### ISSUE TITLE
Need conversion from `toml::de::Error` to `std::io::Error`

### ISSUE THREAD

**Issue by ncihnegn** [toml-rs/toml#591]
It was introduced in https://github.com/toml-rs/toml/commit/c3a89a690aa34a4225126a40d30e9a0bf1f5a5a5 but was dropped in v0.6.
Why was it dropped?

**Comment by epage** [comment]
> Why was it dropped?

The entire crate was rewritten in 0.6 and this was missed when we audited what parts of the API changed (intentionally or not).

More generally our IO support was intentionally dropped in that release because we need the whole document to be loaded to parse, changing those functions from potentially being faster to being convenience which people might not expect.  #578 looks to add it back.  The interesting huccup is we wouldn't be tracking any IO errors that happen to percolate those back up.

Besides that intentional difference due to our different implementations, we tend to follow the [documented conventions](https://serde.rs/conventions.html) and more specifically try to match `serde_json` when it comes to actual serde behavior.

Research  notes
- Original PR is toml-rs/toml-rs#315
- serde_json also supports this ([docs](https://docs.rs/serde_json/latest/serde_json/struct.Error.html#impl-From%3CError%3E-for-Error))
  - It was added in https://github.com/serde-rs/json/commit/e0b45792e8baa0fe39e79980c7e547679c1867b0 without explanation
- serde_yaml does not seem to support it ([docs](https://docs.rs/serde_yaml/latest/serde_yaml/struct.Error.html))

Based on all of that, without a stronger convention I lean towards this just being something people can easily workaround, when needed, with a `map_err`.
