### ISSUE TITLE
`Vec`s containing `Option` types are removed from output

### ISSUE THREAD

**Issue by eievui5** [toml-rs/toml#603]
If a vector contains an option type, and any of its entries are `None`, the vector is completely removed from the output. I believe this is because `toml` tries not to output anything for `None` values, but this chokes when trying to insert a gap with nothing in it.

If you create an enum with the same structure as `Option`, `toml` uses a different format that correctly handles "gaps" (shown in the below example); I believe this should be used for vectors of options.

[Example on Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=640b11e3171204502e51f656fd6e53f1)

**Comment by eievui5** [comment]
The issue seems to be [here](https://github.com/toml-rs/toml/blob/main/crates/toml_edit/src/ser/array.rs#L28)

The `?` bubbles all errors up, including `UnsupportedNone`, despite it having a special meaning. This causes the entire array to be removed. At the very least, `UnsupportedNone` should be transformed into another error:

```rust
let value = match value.serialize(super::ValueSerializer {}) {
    Ok(value) => value,
    Err(Error::UnsupportedNone) => {
        return Err(Error::Custom(String::from(
            "None is unsupported in vectors",
        )))
    }
    Err(e) => return Err(e),
};
```

But supporting `None` in Vectors seems worth it :)

**Comment by epage** [comment]
There are two different ways to look at this bug

The first is that we should be skipping `None` values in arrays like we do with maps.

The other is that we should more generally error.

I lean towards erroring because gaps may be significant and we wouldn't be able to represent that while having a table without a value can be represented.

> If you create an enum with the same structure as Option, toml uses a different format that correctly handles "gaps" (shown in the below example); I believe this should be used for vectors of options.

In the enum case, there is a meaningful way of defining "gaps" based on the definition of your enum.  With options, there isn't any.
