### ISSUE TITLE
The bump on MSRV is preventing `toml_datetime` been use in old system

### ISSUE THREAD

**Issue by cathay4t** [toml-rs/toml#663]
I am using zbus(which depend on toml_datetime) in my project which is targeting RHEL 9.2.

Unfortunately, RHEL 9.2 is has very long support life(5+ years) with rust version carved into stone as 1.66. This somehow break our build system.

Yes, adding `--ignore-rust-version` to cargo build fixed the problem, but that could hide other crates' hard requirements on MSRV.

Your project is bumping MSRV using a robot, there is no line of code indicate this project require rust stable functions which only exists in 1.67+.

**Comment by epage** [comment]
This is intentionally.  They keyword in MSRV is "support".  Our support policy is more strict than what the code can literally run on.  Part of the reason we are proactive is I've found that
- It makes contributors feel more comfortable using new features; otherwise they feel they need to justify bumping the MSRV
- It makes the MSRV policy clear to users.  Clap went dark for several years and people got used to the long-lived MSRV from that and got upset when development resumed and MSRV was bumped even though nothing had changed in the policy. 

If you have access to nightly, I'd recommend doing dependency resolution on nightly with `-Zmsrv-policy` as that will ensure you get compatible dependencies.  The RFC for this is at rust-lang/rfcs#3537
