### ISSUE TITLE
Expose line and column in deserialization errors

### ISSUE THREAD

**Issue by ehuss** [toml-rs/toml#667]
The `de::Error` type used to have a `line_col()` method that would return the line and column numbers where the error occurred. At some point this seems to have been removed. This was useful for being able to provide structured errors to the user. The error type now has span information (nice!), but that now requires using tricky and error-prone code like [`translate_position`](https://github.com/rust-lang/cargo/blob/7bb7b539558dc88bea44cee4168b6269bf8177b0/src/cargo/util/toml/mod.rs#L2178-L2206). Would it be possible to provide something that translates the span to something like `(start_line, start_col, end_line, end_col)`?

**Comment by epage** [comment]
This was an intentional decision.  Column counts are dependent on the output medium and even a decent general approximation would require pulling in more dependencies.

Rather than trying to get something that would work for these cases, we've left it to presentation layers.  In cargo's case, we are instead looking at putting the translation in `annotate-snippets`.  We're just cataloging the breaking changes as we go and will clean it up.

**Comment by ehuss** [comment]
That makes sense. It ended up for my use case that I only really needed line numbers, which are pretty easy to compute from the span. I'll go ahead and close.
