### ISSUE TITLE
Differentiating syntax from schema errors

### ISSUE THREAD

**Issue by konstin** [toml-rs/toml#778]
I would to add a specific hint to the error message when there is a schema violation, but not if the toml syntax is wrong. Would it be possible to add an error message to tell theese apart?

Minimal example: I'd like to attach context to the first error, but pass the second one on without context.
```rust
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Metadata {
    name: String,
    version: String,
}

fn main() {
    println!(
        "{:?}",
        toml::from_str::<Metadata>(
            r#"
            version = "0.1.0"
            "#
        )
    );
    println!(
        "{:?}",
        toml::from_str::<Metadata>(
            r#"
            invalid syntax
            version = "0.1.0"
            "#
        )
    );
}
```

**Comment by epage** [comment]
Could you expand on why you need this done in post-processing rather than being able to report it when deserializing the type?

For now, we've been focusing on keeping the error type's API simple for easy API compatibility as crates like to put `toml::Value` in their API, like `cargo_metadata`.  If we go down this route, we should consider more holistically the needs for deserialization errors.  For example, someone from Cargo was asking about having more individual pieces of information from serde errors to better format errors using annotate-snippets.

**Comment by konstin** [comment]
Mainly because i have complex types for which i'd like to use `#[derive(Serialize, Deserialize)]` over manual serde impl that is much harder to write and maintain. I'm looking for something like `Error::is_toml` or `Error::is_serde` that tracks the level on which the error occurred.

**Comment by konstin** [comment]
Thank you, that's perfect!
