### ISSUE TITLE
[Discussion] `abi_stable` for toml Value

### ISSUE THREAD

**Issue by Atreyagaurav** [toml-rs/toml#779]
Hi, I've been using this crate to read toml files for one of my programs, but I'm considering the options for a plugin system.  The problem I came across is that I need stable abi for the data types and the crate `abi_stable` will only help for the crates I write not for external crate.

I was thinking of making a pull request like others have for other libraries, where we add a feature `sabi`, which would make the types like `toml::Value` abi stable. Since it uses String and HashMap and Vec, those things need to be replaced by other types like `RString`, `RHashMap`, `RVec` etc. I think it might require a lot of code change so I don't know if it is something open for the crate developers.

Alternative might be to write another library with new types, but that is a lot of extra work. So I'm asking here in case you think it is a good idea to add to this crate.

**Comment by epage** [comment]
I'm hesitant to pull in other crates, even optionally, as that increases the compatibility surface of our API, making it harder to maintain compatbility.

Also, if this is behind a feature, we can't replace public types with alternative versions because that would be a breaking change and adding of a feature should not break an API.

> [Discussion] 

Out of curiosity, is there a reason you didn't use https://github.com/toml-rs/toml/discussions

**Comment by Atreyagaurav** [comment]
Yeah, changing the types is not something that should be done if the feature is not active. 

I was thinking using `cfg` to make the enum member `Value::String` hold `RString` if feature is activated, otherwise `String`. But then we'll have to supply extra methods every time those members are used. Which should be doable, and because of rust, we probably won't miss anything. Right now I don't know how much extra work that would be. At least conversion of std types to `abi_stable` types seems to be O(1), and we only need alternative for String, Array, Table.

If you don't want to add that feature to the crate, it is fine. I'm thinking of either making a type and converting to/from toml::Value, or making a different crate with minimal support of toml specification. I am just hoping to not have to do that if it can be added here, since that might benefit more people along the line. 

Sorry, I didn't know about the discussions.

**Comment by epage** [comment]
> Yeah, changing the types is not something that should be done if the feature is not active.

Activating a feature should not change types.  A crate in your dependency graph that activates a feature should not break another crate in your dependency graph that depends on that same package without the feature.  This is part of what we mean when we say that features must be "additive".

Since we can't conditonally add support for this, I'm going to close this.  That is leaving aside the question of API stability that would also be a concern for doing this.

> If you don't want to add that feature to the crate, it is fine. I'm thinking of either making a type and converting to/from toml::Value, or making a different crate with minimal support of toml specification

All you need is a serde-compatible type.  Everything else of TOML can be taken care of by `toml` or `toml_edit`.
