### ISSUE TITLE
`toml_edit`: `toml_edit::value` returns an `Item`, not a `Value`

### ISSUE THREAD

**Issue by teythoon** [toml-rs/toml#790]
```rust
pub fn value<V: Into<Value>>(v: V) -> Item
```

Further, the documentation says it returns a formatted value.

This seems to be either an oversight from a previous refactoring, or an ingenious attempt of gaslighting downstream consumers ;)

**Comment by epage** [comment]
> Further, the documentation says it returns a formatted value.
>
> This seems to be either an oversight from a previous refactoring, or an ingenious attempt of gaslighting downstream consumers ;)

Neither.  It is doing what its saying.  It [says](https://docs.rs/toml_edit/latest/toml_edit/fn.value.html)

> Returns a formatted value.

In contrast to

> Returns a formatted `Value`.

In TOML semantics, it is returning a value and that is carried over in it being an `Item::Value`. 

The API is optimized for [`DocumentMut::index_mut`](https://docs.rs/toml_edit/latest/toml_edit/struct.DocumentMut.html#impl-IndexMut%3C%26str%3E-for-DocumentMut) and [`Table::index_mut`](https://docs.rs/toml_edit/latest/toml_edit/struct.Table.html#impl-IndexMut%3C%26str%3E-for-Table) for quick creation of a document, rather than any calls on `InlineTable` or `Array`.

e.g. code like
https://github.com/toml-rs/toml/blob/0b4cf74420cc65e04e909945f48a36a19370327c/crates/toml_edit/tests/testsuite/edit.rs#L166-L168

**Comment by teythoon** [comment]
As a new user of toml_edit, the most challenging aspect of its API was that it is so inhomogeneous.  Depending on what kind of object you have, doing a `get` or an `iter` may give you `Item`s, `Array`s, or `Value`s.  That is a significant cognitive burden.

On top of that, having a function called value that returns an item doesn't help.

**Comment by epage** [comment]
`get` and `iter` are generally returning the most specific types which gives you type level feedback on what you can do, rather than having to assume and `unwrap`.   
Doing this is fairly idiomatic in Rust.  It is made worse by TOML having two different kinds of arrays and tables.

`value` doesn't because it was generally geared for a different purpose (inserting into Tables)

At this time, I do not see us changing this part of the API
